config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers
  end

  resources :answers

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  root to: 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :description, presence: true
    # length: { minimum: 50 }
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, presence: true
  # length: { minimum: 40 }
  validates :description, presence: true
  # length: { minimum: 150 }
  has_many :answers, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.image = auth["info"]["image"]
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @answer = Answer.new(answer_params)
    # currently @answer question_id is null
    @answer.question_id = params[:question_id]
    # set @answer question_id to the params question_id
    if @answer.save
      redirect_to question_path(@answer.question), notice: "You have successfully posted your answer."
    else
      flash[:notice] = "Your description is not long enough"
      redirect_to question_path(@answer.question)
    end
  end

  def update
    @answer = Answer.find(params[:id])
    @answer.best_answer_count += 1
    @answer.save
    redirect_to(question_path(@answer.question))
  end

  private

  def answer_params
    params.require(:answer).permit(:description)
    binding.pry
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def current_user
    user_id = session[:user_id]
    @current_user ||= User.find(user_id) if user_id.present?
  end

  def signed_in?
    current_user.present?
  end


  def set_current_user(user)
    session[:user_id] = user.id
  end

  def authenticate!
    unless signed_in?
      flash[:notice] = 'You need to sign in if you want to do that!'
      redirect_to questions_path
    end
  end

  def index
    @questions = Question.all.order(updated_at: :desc)
    binding.pry
  end

  def new
    authenticate!
    @question = Question.new
  end

  def create

    @question = Question.new(question_params)

    if @question.save
      flash[:notice] = "You have successfully posted your question."
      redirect_to @question
    end

    # if question_params["title"].length < 40
    #   flash[:notice] = "Your title is not long enough"
    #   render :new
    # elsif question_params["description"].length < 150
    #   flash[:notice] = "Your description is not long enough"
    #   render :new
    # else @question.save
    #   redirect_to @question, notice: "You have successfully posted your question."
    # end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = Answer.all.where("question_id = ?", params[:id]).order(best_answer_count: :desc)
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:notice] = "Success"

      redirect_to question_path
    else
      flash[:notice] = "Did not save try again"
      # if description or title is too short will display this message
      # not very information
      render :new
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:notice] = "You have deleted this question."

    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, notice: "signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
    signed in as <img src="<%=current_user.image%>" class="avatar"><strong><%= current_user.name %></strong>!
    <%= link_to "sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "sign in with Twitter", "/auth/twitter", id: "sign_in" %>
  <% end %>

  <% if flash.any? %>
    <h1><%= flash[:notice] %></h1>
  <% end %>
<%= yield %>

</body>
</html>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= link_to "delete", @question, method: :delete %>
<br>
<br>
<%= form_for @question do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %>
  <br>
  <br>
  <%= f.label :description %>:
  <%= f.text_area :description %>
  <br>
  <br>
  <%= f.submit %>
<% end %>

app/views/questions/index.html.erb
<%= link_to "Create New Question", new_question_path %>
<ul>
  <% @questions.each do |question| %>
    <li><%= link_to "#{question.title}", question_path(question) %> - <%= link_to 'edit', edit_question_path(question) %> <%= link_to 'delete', question, method: :delete %><br>
</li>
  <% end %>
</ul>

app/views/questions/new.html.erb
<%= form_for @question do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title, required: true %><br>

  <%= f.label :description %>:
  <%= f.text_area :description %><br>

  <%= f.submit %>
<% end %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<p><%= @question.description %></p>
<br>
<%= link_to "Edit", edit_question_path %> <%= link_to "Delete", @question, method: :delete%>
<br>
<ul>
  <% @answers.each do |answer| %>
    <li><%= button_to '+1', answer_path(answer), method: :put, action: "update" %> <%= answer.best_answer_count %> <%= answer.created_at %> <%= answer.description %></li>
  <% end %>
</ul>
<br>

<%= form_for [@question, @answer] do |f| %>
  <%= f.label :answer %>:
  <%= f.text_area :description, required: true %>
  <br>
  <br>
  <%= f.submit %>
<% end %>